version: '3.8'

services:
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./laravel:/var/www/html        
    networks:
      - laravel
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
      sleep 15 &&
      cp .env.example .env ||
      php artisan key:generate ||
      composer install &&
      php artisan config:clear &&
      php artisan migrate --force &&
      php-fpm
      "
      
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html        
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop_catalog
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 40s
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
     # - ./sql/test.sql:/docker-entrypoint-initdb.d/test.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data: {}
